apiVersion: v1
kind: Service
metadata:
  name: svc-app01
spec:
  selector:
    app: app01
  ports:
  - protocol: "TCP"
    port: 3010
    targetPort: 5000
  type: NodePort
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
spec:
  selector:
    matchLabels:
      app: app01
  replicas: 1
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
      - name: hello-python
        image: gru.ocir.io/grfufo4rgagz/springtest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: ocir
